version: '3.1'

services:
  db:
    image: mysql:8
    container_name: bankdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vue_bank
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: bankpassword
    ports:
      - "3306:3306"
